### ISSUE TITLE
Links Drop down not working or all pages

### ISSUE THREAD

**Issue by gitchrisadams** [ProgrammersLearningTogetherWesterly/plt-rails-website#5]
Not working for About, Members, Treasury, Chat,

**Comment by andrewborstein** [comment]
The "Links" drop down <em>does</em> actually work on every page, but only after a page refresh. I think this is because pages are loaded in rails via [turbo links](https://github.com/rails/turbolinks) and bootstrap js (which powers the dropdown) only gets called on `document.ready` i.e. each time the page is loaded fresh. Installing [jQuery turbolinks](https://github.com/kossnocorp/jquery.turbolinks) should solve the problem — I'll try it locally to verify.

**Comment by andrewborstein** [comment]
Fixed with jQuery Turbo Links. Changes have been pushed to the master.
